export const INDIAN_PLACES = [
  { name: "Mumbai", district: "Mumbai", state: "Maharashtra" },
  { name: "Pune", district: "Pune", state: "Maharashtra" },
  { name: "Nagpur", district: "Nagpur", state: "Maharashtra" },
  { name: "Nashik", district: "Nashik", state: "Maharashtra" },
  { name: "Aurangabad", district: "Aurangabad", state: "Maharashtra" },
  { name: "Solapur", district: "Solapur", state: "Maharashtra" },
  { name: "Amravati", district: "Amravati", state: "Maharashtra" },
  { name: "Baramati", district: "Pune", state: "Maharashtra" },
  { name: "Bhiwandi", district: "Thane", state: "Maharashtra" },
  { name: "Navi Mumbai", district: "Thane", state: "Maharashtra" },
  { name: "Thane", district: "Thane", state: "Maharashtra" },
  { name: "Bhopal", district: "Bhopal", state: "Madhya Pradesh" },
  { name: "Indore", district: "Indore", state: "Madhya Pradesh" },
  { name: "Jabalpur", district: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Gwalior", district: "Gwalior", state: "Madhya Pradesh" },
  { name: "Ujjain", district: "Ujjain", state: "Madhya Pradesh" },
  { name: "Bengaluru", district: "Bengaluru Urban", state: "Karnataka" },
  { name: "Mysuru", district: "Mysuru", state: "Karnataka" },
  { name: "Hubballi", district: "Dharwad", state: "Karnataka" },
  { name: "Delhi", district: "Central Delhi", state: "Delhi" },
  { name: "Noida", district: "Gautam Buddha Nagar", state: "Uttar Pradesh" },
  { name: "Ghaziabad", district: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Lucknow", district: "Lucknow", state: "Uttar Pradesh" },
  { name: "Kanpur", district: "Kanpur Nagar", state: "Uttar Pradesh" },
  { name: "Agra", district: "Agra", state: "Uttar Pradesh" },
  { name: "Meerut", district: "Meerut", state: "Uttar Pradesh" },
  { name: "Varanasi", district: "Varanasi", state: "Uttar Pradesh" },
  { name: "Allahabad", district: "Prayagraj", state: "Uttar Pradesh" },
  { name: "Gorakhpur", district: "Gorakhpur", state: "Uttar Pradesh" },
  { name: "Bareilly", district: "Bareilly", state: "Uttar Pradesh" },
  { name: "Moradabad", district: "Moradabad", state: "Uttar Pradesh" },
  { name: "Saharanpur", district: "Saharanpur", state: "Uttar Pradesh" },
  { name: "Jhansi", district: "Jhansi", state: "Uttar Pradesh" },
  { name: "Aligarh", district: "Aligarh", state: "Uttar Pradesh" },
  { name: "Loni", district: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Jaipur", district: "Jaipur", state: "Rajasthan" },
  { name: "Jodhpur", district: "Jodhpur", state: "Rajasthan" },
  { name: "Kota", district: "Kota", state: "Rajasthan" },
  { name: "Ajmer", district: "Ajmer", state: "Rajasthan" },
  { name: "Udaipur", district: "Udaipur", state: "Rajasthan" },
  { name: "Bikaner", district: "Bikaner", state: "Rajasthan" },
  { name: "Jamnagar", district: "Jamnagar", state: "Gujarat" },
  { name: "Vadodara", district: "Vadodara", state: "Gujarat" },
  { name: "Surat", district: "Surat", state: "Gujarat" },
  { name: "Ahmedabad", district: "Ahmedabad", state: "Gujarat" },
  { name: "Rajkot", district: "Rajkot", state: "Gujarat" },
  { name: "Bhavnagar", district: "Bhavnagar", state: "Gujarat" },
  { name: "Chennai", district: "Chennai", state: "Tamil Nadu" },
  { name: "Coimbatore", district: "Coimbatore", state: "Tamil Nadu" },
  { name: "Madurai", district: "Madurai", state: "Tamil Nadu" },
  { name: "Hyderabad", district: "Hyderabad", state: "Telangana" },
  { name: "Vijayawada", district: "Krishna", state: "Andhra Pradesh" },
  { name: "Visakhapatnam", district: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Kolkata", district: "Kolkata", state: "West Bengal" },
  { name: "Howrah", district: "Howrah", state: "West Bengal" },
  { name: "Siliguri", district: "Darjeeling", state: "West Bengal" },
  { name: "Cuttack", district: "Cuttack", state: "Odisha" },
  { name: "Ranchi", district: "Ranchi", state: "Jharkhand" },
  { name: "Dhanbad", district: "Dhanbad", state: "Jharkhand" },
  { name: "Jamshedpur", district: "East Singhbhum", state: "Jharkhand" },
  { name: "Patna", district: "Patna", state: "Bihar" },
  { name: "Guwahati", district: "Kamrup Metropolitan", state: "Assam" },
  { name: "Srinagar", district: "Srinagar", state: "Jammu and Kashmir" },
  { name: "Amritsar", district: "Amritsar", state: "Punjab" },
  { name: "Ludhiana", district: "Ludhiana", state: "Punjab" },
  { name: "Dehradun", district: "Dehradun", state: "Uttarakhand" },
  { name: "Kochi", district: "Ernakulam", state: "Kerala" },
  { name: "Raipur", district: "Raipur", state: "Chhattisgarh" },
  { name: "Bhilai", district: "Durg", state: "Chhattisgarh" },
  { name: "Dharwad", district: "Dharwad", state: "Karnataka" },
  { name: "Belagavi", district: "Belagavi", state: "Karnataka" },
  { name: "Mangaluru", district: "Dakshina Kannada", state: "Karnataka" },
  { name: "Tirupati", district: "Tirupati", state: "Andhra Pradesh" },
  { name: "Guntur", district: "Guntur", state: "Andhra Pradesh" },
  { name: "Kurnool", district: "Kurnool", state: "Andhra Pradesh" },
  { name: "Nellore", district: "Nellore", state: "Andhra Pradesh" },
  { name: "Tirunelveli", district: "Tirunelveli", state: "Tamil Nadu" },
  { name: "Salem", district: "Salem", state: "Tamil Nadu" },
  { name: "Erode", district: "Erode", state: "Tamil Nadu" },
  { name: "Trichy", district: "Tiruchirappalli", state: "Tamil Nadu" },
  { name: "Bhubaneswar", district: "Khordha", state: "Odisha" },
  { name: "Rourkela", district: "Sundargarh", state: "Odisha" },
  { name: "Puri", district: "Puri", state: "Odisha" },
  { name: "Shirdi", district: "Ahilyanagar", state: "Maharashtra" },
  { name: "Satara", district: "Satara", state: "Maharashtra" },
  { name: "Kolhapur", district: "Kolhapur", state: "Maharashtra" },
  { name: "Sangli", district: "Sangli", state: "Maharashtra" },
  { name: "Wardha", district: "Wardha", state: "Maharashtra" },
  { name: "Yavatmal", district: "Yavatmal", state: "Maharashtra" },
  { name: "Bharuch", district: "Bharuch", state: "Gujarat" },
  { name: "Anand", district: "Anand", state: "Gujarat" },
  { name: "Mehsana", district: "Mehsana", state: "Gujarat" },
  { name: "Junagadh", district: "Junagadh", state: "Gujarat" },
  { name: "Surendranagar", district: "Surendranagar", state: "Gujarat" },
  { name: "Kakinada", district: "Kakinada", state: "Andhra Pradesh" },
  { name: "Tiruppur", district: "Tiruppur", state: "Tamil Nadu" },
  { name: "Karur", district: "Karur", state: "Tamil Nadu" },
  { name: "Hosur", district: "Krishnagiri", state: "Tamil Nadu" },
  { name: "Srikakulam", district: "Srikakulam", state: "Andhra Pradesh" },
  { name: "Warangal", district: "Warangal", state: "Telangana" },
  { name: "Nizamabad", district: "Nizamabad", state: "Telangana" },
  { name: "Khammam", district: "Khammam", state: "Telangana" },
  { name: "Palakkad", district: "Palakkad", state: "Kerala" },
  { name: "Thrissur", district: "Thrissur", state: "Kerala" },
  { name: "Kollam", district: "Kollam", state: "Kerala" },
  { name: "Kozhikode", district: "Kozhikode", state: "Kerala" },
  { name: "Bokaro", district: "Bokaro", state: "Jharkhand" },
  { name: "Hazaribagh", district: "Hazaribagh", state: "Jharkhand" },
  { name: "Durgapur", district: "Paschim Bardhaman", state: "West Bengal" },
  { name: "Asansol", district: "Paschim Bardhaman", state: "West Bengal" },
  { name: "Muzaffarpur", district: "Muzaffarpur", state: "Bihar" },
  { name: "Bhagalpur", district: "Bhagalpur", state: "Bihar" },
  { name: "Gaya", district: "Gaya", state: "Bihar" },
  { name: "Darbhanga", district: "Darbhanga", state: "Bihar" },
  { name: "Sonepat", district: "Sonepat", state: "Haryana" },
  { name: "Gurugram", district: "Gurugram", state: "Haryana" },
  { name: "Faridabad", district: "Faridabad", state: "Haryana" },
  { name: "Rohtak", district: "Rohtak", state: "Haryana" },
  { name: "Hisar", district: "Hisar", state: "Haryana" },
  { name: "Bhilwara", district: "Bhilwara", state: "Rajasthan" },
  { name: "Kishanganj", district: "Kishanganj", state: "Bihar" },
  { name: "Bokaro Steel City", district: "Bokaro", state: "Jharkhand" },
  { name: "Dhanera", district: "Banaskantha", state: "Gujarat" },
  { name: "Palanpur", district: "Banaskantha", state: "Gujarat" },
  { name: "Bharatpur", district: "Bharatpur", state: "Rajasthan" },
  { name: "Sikar", district: "Sikar", state: "Rajasthan" },
  { name: "Alwar", district: "Alwar", state: "Rajasthan" },
  { name: "Pali", district: "Pali", state: "Rajasthan" },
  { name: "Jhalawar", district: "Jhalawar", state: "Rajasthan" },
  { name: "Sambalpur", district: "Sambalpur", state: "Odisha" },
  { name: "Cuddalore", district: "Cuddalore", state: "Tamil Nadu" },
  { name: "Dindigul", district: "Dindigul", state: "Tamil Nadu" },
  { name: "Kanchipuram", district: "Kanchipuram", state: "Tamil Nadu" }
];

export const buildIndianPlaceSuggestions = (query = "") => {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return [];

  const matches = INDIAN_PLACES.filter((place) => {
    const name = place.name.toLowerCase();
    const district = (place.district || "").toLowerCase();
    const state = (place.state || "").toLowerCase();
    return name.startsWith(trimmed) || name.includes(trimmed) || district.includes(trimmed) || state.includes(trimmed);
  });

  const unique = [];
  const seen = new Set();

  matches.forEach((place) => {
    const key = `${place.name.toLowerCase()}|${place.district.toLowerCase()}|${place.state.toLowerCase()}`;
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(place);
    }
  });

  return unique.slice(0, 12).map((place) => ({
    display_name: `${place.name}, ${place.district}, ${place.state}, India`,
    lat: 0,
    lon: 0,
    address: {
      city: place.name,
      town: place.name,
      village: place.name,
      district: place.district,
      state: place.state,
      country: "India",
      country_code: "in",
    },
    type: "city",
    class: "place",
    source: "local-data",
  }));
};
